const OuttrackerTypes = {
    ADD_MESSAGE_TO_CHAT_HISTORY: 'ADD_MESSAGE_TO_CHAT_HISTORY',
    CREATE_OUTAGE: 'CREATE_OUTAGE',
    END_OUTAGE: 'END_OUTAGE',
    RESET_STORE: 'RESET_STORE',
    RECORD_INPUT_TO_OUTAGE: 'RECORD_INPUT_TO_OUTAGE',
    ADD_DESCIBE_TO_OUTAGE: 'ADD_DESCIBE_TO_OUTAGE',
    SET_IS_RECORDING_ALL_INPUTS: 'SET_IS_RECORDING_ALL_INPUTS',
}


export default OuttrackerTypes
